from gensim.summarization import summarize

sentence="Finland testing two suspected coronavirus cases. Authorities in south-eastern Finland said Wednesday afternoon that a second individual was being tested for Covid-19. Health officials in Jyväskylä are investigating whether a patient exhibiting symptoms of an upper respiratory tract infection has contracted novel coronavirus (Covid-19). Meanwhile, health authorities in south-eastern Finland said on Wednesday afternoon that another patient was being tested for the virus. Results from a coronavirus test on the first patient at Central Finland Hospital will be ready on Thursday morning, health officials said on Wednesday. On Tuesday evening the patient travelled by train from Helsinki International Airport via Tikkurila and Tampere to Jyväskylä. State railways VR said the passenger self-reported symptoms to train staff. VR said it has removed a number of train cars as a precautionary measure. The company said it plans to disinfect the carriages before returning them to service. Second suspected case in South Savo; Meanwhile, the second patient in south-east Finland was also being tested for Covid-19 on Wednesday, the South Savo Social and Health Care Authority (Essote) announced on Wednesday afternoon. That individual is awaiting lab results which are also expected on Thursday, but Essote said that, based on preliminary information, the chances of the patient having Covid-19 were low. The South Savo health authority said it would offer more information by noon on Thursday. Finnish hospitals have so far performed some 30 coronavirus tests, one of which came back positive last month. The patient was a 32-year-old Chinese woman visiting Lapland who has since been released from hospital when tests determined she was symptom-free. Some 300 coronavirus have been confirmed in Europe to date, the majority in Italy.On Wednesday the Finnish government announced plans to meet Thursday to ramp up preparedness to deal with the disease. Story updated 26 February 2020 at 4:12pm to reflect that a second patient was being tested for the virus in South Savo."

print(summarize(sentence))

#Health officials in Jyväskylä are investigating whether a patient exhibiting symptoms of an upper respiratory tract infection has
#contracted novel coronavirus (Covid-19). Meanwhile, health authorities in south-eastern Finland said on Wednesday afternoon that 
#another patient was being tested for the virus. Results from a coronavirus test on the first patient at Central Finland Hospital will 
#be ready on Thursday morning, health officials said on Wednesday.On Tuesday evening the patient travelled by train from Helsinki
#International Airport via Tikkurila and Tampere to Jyväskylä. State railways VR said the passenger self-reported symptoms to train 
#staff. VR said it has removed a number of train cars as a precautionary measure. The company said it plans to disinfect the carriages
#before returning them to service. Second suspected case in South Savo Meanwhile, the second patient in south-east Finland was also 
#being tested for Covid-19 on Wednesday, the South Savo Social and Health Care Authority (Essote) announced on Wednesday afternoon.
#That individual is awaiting lab results which are also expected on Thursday, but Essote said that, based on preliminary information, 
#the chances of the patient having Covid-19 were low. The South Savo health authority said it would offer more information by noon on 
#Thursday. Finnish hospitals have so far performed some 30 coronavirus tests, one of which came back positive last month. The patient 
#was a 32-year-old Chinese woman visiting Lapland who has since been released from hospital when tests determined she was symptom-free.
#Some 300 coronavirus have been confirmed in Europe to date, the majority in Italy. On Wednesday the Finnish government announced plans
#to meet Thursday to ramp up preparedness to deal with the disease. Story updated 26 February 2020 at 4:12pm to reflect that a second
#patient was being tested for the virus in South.